name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Configuring JDK 20
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: 'maven'

      - name: Test Maven
        run: mvn test